---
sudo: required
language: python
cache: pip
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  - sudo add-apt-repository  "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce docker-ce-cli containerd.io
install:
  - pip install molecule docker
script:
  - molecule test
