---

- name: create prometheus group
  group:
    name: "{{ prometheus_user }}"
    gid: 999
    state: present

- name: create prometheus user
  user:
    name: "{{ prometheus_user }}"
    comment: prometheus service user
    uid: 999
    shell: /bin/false
    group: "{{ prometheus_user }}"
