---

- name: download prometheus files
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.6.0/prometheus-2.6.0.linux-amd64.tar.gz
    dest: /tmp/prometheus-2.6.0.linux-amd64.tar.gz

- name: uncompress the prometheus files
  unarchive:
    src: /tmp/prometheus-2.6.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: copy executables into place
  copy:
    src: "/tmp/prometheus-2.6.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    remote_src: yes
  with_items:
    - prometheus
    - promtool

- name: copy directories into /etc/prometheus
  copy:
    src: "/tmp/prometheus-2.6.0.linux-amd64/{{ item }}"
    dest: "{{ prometheus_etc_dir }} "
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    remote_src: yes
  with_items:
    - consoles
    - console_libraries

- name: set prometheus.yml template
  template:
    src: templates/prometheus.yml.j2
    dest: "{{ prometheus_etc_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
